name: "Coder Desktop"
options:
  bundleIdPrefix: com.coder
  deploymentTarget:
    macOS: "14.6"
  xcodeVersion: "1600"
  minimumXcodeGenVersion: "2.42.0"

settings:
  base:
    MARKETING_VERSION: "1.0" # Sets the version number.
    CURRENT_PROJECT_VERSION: "1" # Sets the build number.

    ALWAYS_SEARCH_USER_PATHS: NO
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    COPY_PHASE_STRIP: NO
    DEAD_CODE_STRIPPING: YES
    DEVELOPMENT_TEAM: "4399GN35BJ"
    GENERATE_INFOPLIST_FILE: YES
    PRODUCT_NAME: "$(TARGET_NAME)"
    SWIFT_VERSION: ${SWIFT_VERSION}
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    LD_RUNPATH_SEARCH_PATHS:
      - "$(inherited)"
      - "@executable_path/../Frameworks"
      - "@loader_path/Frameworks"
    GCC_C_LANGUAGE_STANDARD: gnu17
    CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
    CLANG_ENABLE_MODULES: YES
    CLANG_ENABLE_OBJC_ARC: YES
    CLANG_ENABLE_OBJC_WEAK: YES
    ENABLE_STRICT_OBJC_MSGSEND: YES
    CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
    CLANG_WARN_BOOL_CONVERSION: YES
    CLANG_WARN_COMMA: YES
    CLANG_WARN_CONSTANT_CONVERSION: YES
    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
    CLANG_WARN_DIRECT_OBJC_ISA_USAGE: YES_ERROR
    CLANG_WARN_DOCUMENTATION_COMMENTS: YES
    CLANG_WARN_EMPTY_BODY: YES
    CLANG_WARN_ENUM_CONVERSION: YES
    CLANG_WARN_INFINITE_RECURSION: YES
    CLANG_WARN_INT_CONVERSION: YES
    CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
    CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
    CLANG_WARN_OBJC_ROOT_CLASS: YES_ERROR
    CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
    CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
    CLANG_WARN_STRICT_PROTOTYPES: YES
    CLANG_WARN_SUSPICIOUS_MOVE: YES
    CLANG_WARN_UNGUARDED_AVAILABILITY: YES_AGGRESSIVE
    CLANG_WARN_UNREACHABLE_CODE: YES
    CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
    GCC_WARN_64_TO_32_BIT_CONVERSION: YES
    GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
    GCC_WARN_UNDECLARED_SELECTOR: YES
    GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
    GCC_WARN_UNUSED_FUNCTION: YES
    GCC_WARN_UNUSED_VARIABLE: YES
    GCC_NO_COMMON_BLOCKS: YES
    CLANG_ANALYZER_NONNULL: YES
    CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: YES_AGGRESSIVE
    MTL_FAST_MATH: YES
    LOCALIZATION_PREFERS_STRING_CATALOGS: YES
  configs:
    debug:
      GCC_PREPROCESSOR_DEFINITIONS:
        - "DEBUG=1"
        - "$(inherited)"
      ONLY_ACTIVE_ARCH: YES
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG $(inherited)"
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
      GCC_OPTIMIZATION_LEVEL: 0
      DEBUG_INFORMATION_FORMAT: dwarf
      ENABLE_TESTABILITY: YES
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
    release:
      SWIFT_COMPILATION_MODE: wholemodule
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
      ENABLE_NS_ASSERTIONS: NO
      MTL_ENABLE_DEBUG_INFO: NO

packages:
  ViewInspector:
    url: https://github.com/nalexn/ViewInspector
    from: 0.10.0
  SwiftLintPlugins:
    url: https://github.com/SimplyDanny/SwiftLintPlugins
    from: 0.57.1
  FluidMenuBarExtra:
    url: https://github.com/lfroms/fluid-menu-bar-extra
    from: 1.1.0
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess
    branch: e0c7eebc5a4465a3c4680764f26b7a61f567cdaf
  SwiftProtobuf:
    url: https://github.com/apple/swift-protobuf.git
    exactVersion: 1.28.2
  Mocker:
    url: https://github.com/WeTransfer/Mocker
    from: 3.0.2
  LaunchAtLogin:
    url: https://github.com/sindresorhus/LaunchAtLogin-modern
    from: 1.1.0

targets:
  Coder Desktop:
    type: application
    platform: macOS
    sources:
      - path: Coder Desktop
    entitlements:
      path: Coder Desktop/Coder_Desktop.entitlements
      properties:
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider
        com.apple.developer.system-extension.install: true
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-only: true
        com.apple.security.network.client: true
        com.apple.security.application-groups:
          - $(TeamIdentifierPrefix)com.coder.Coder-Desktop
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon # Sets the app icon to "AppIcon".
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: YES
        DEVELOPMENT_ASSET_PATHS: '"Coder Desktop/Preview Content"' # Adds development assets.
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_PREVIEWS: YES
        INFOPLIST_KEY_LSUIElement: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        SWIFT_EMIT_LOC_STRINGS: YES
        PRODUCT_BUNDLE_IDENTIFIER: "com.coder.Coder-Desktop"

        # (ThomasK33): Install the application into the /Applications folder
        # so that macOS stops complaining about the app being run from an
        # untrusted folder.
        DEPLOYMENT_LOCATION: YES
        DSTROOT: $(LOCAL_APPS_DIR)/Coder
        INSTALL_PATH: /
        SKIP_INSTALL: NO
    dependencies:
      - target: CoderSDK
        embed: true
      - target: VPNXPC
        embed: true
      - target: VPN
        embed: without-signing # Embed without signing.
      - package: FluidMenuBarExtra
      - package: KeychainAccess
      - package: LaunchAtLogin
    scheme:
      testPlans:
        - path: Coder Desktop.xctestplan
      testTargets:
        - Coder DesktopTests
        - Coder DesktopUITests
    buildToolPlugins:
      - plugin: SwiftLintBuildToolPlugin
        package: SwiftLintPlugins

  Coder DesktopTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Coder DesktopTests
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Coder Desktop.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Coder Desktop"
        PRODUCT_BUNDLE_IDENTIFIER: "com.coder.Coder-DesktopTests"
    dependencies:
      - target: "Coder Desktop"
      - target: CoderSDK
        embed: false # Do not embed the framework.
      - package: ViewInspector
      - package: Mocker

  Coder DesktopUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: Coder DesktopUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.coder.Coder-DesktopUITests"
    dependencies:
      - target: Coder Desktop

  VPN:
    type: system-extension
    platform: macOS
    sources:
      - path: VPN
    entitlements:
      path: VPN/VPN.entitlements
      properties:
        com.apple.developer.networking.networkextension:
          - packet-tunnel-provider
        com.apple.security.app-sandbox: true
        com.apple.security.application-groups:
          - $(TeamIdentifierPrefix)com.coder.Coder-Desktop
        com.apple.security.network.client: true
        com.apple.security.network.server: true
    settings:
      base:
        ENABLE_HARDENED_RUNTIME: YES
        INFOPLIST_FILE: VPN/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: "com.coder.Coder-Desktop.VPN"
        PRODUCT_MODULE_NAME: "$(PRODUCT_NAME:c99extidentifier)"
        PRODUCT_NAME: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_OBJC_BRIDGING_HEADER: "VPN/com_coder_Coder_Desktop_VPN-Bridging-Header.h"
    dependencies:
      - target: VPNLib
        embed: true
      - target: CoderSDK
        embed: true
      - target: VPNXPC
        embed: true
      - sdk: NetworkExtension.framework

  VPNLib:
    type: framework
    platform: macOS
    sources:
      - path: VPNLib
    settings:
      base:
        PRODUCT_NAME: "$(TARGET_NAME:c99extidentifier)"
        SWIFT_EMIT_LOC_STRINGS: YES
        PRODUCT_BUNDLE_IDENTIFIER: "com.coder.Coder-Desktop.VPNLib"
        DYLIB_COMPATIBILITY_VERSION: 1
        DYLIB_CURRENT_VERSION: 1
        DYLIB_INSTALL_NAME_BASE: "@rpath"
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Automatic
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
          - "@loader_path/Frameworks"
    scheme:
      testTargets:
        - VPNLibTests
    dependencies:
      - package: SwiftProtobuf
      - package: SwiftProtobuf
        product: SwiftProtobufPluginLibrary
      - target: CoderSDK
        embed: false

  VPNLibTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: VPNLibTests
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Coder Desktop.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Coder Desktop"
        PRODUCT_BUNDLE_IDENTIFIER: "com.coder.Coder-Desktop.VPNLibTests"
    dependencies:
      - target: Coder Desktop
      - target: VPNLib
        embed: false
      - package: Mocker

  CoderSDK:
    type: framework
    platform: macOS
    sources:
      - path: CoderSDK
    settings:
      base:
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        PRODUCT_NAME: "$(TARGET_NAME:c99extidentifier)"
        SWIFT_EMIT_LOC_STRINGS: YES
        GENERATE_INFOPLIST_FILE: YES
        DYLIB_COMPATIBILITY_VERSION: 1
        DYLIB_CURRENT_VERSION: 1
        DYLIB_INSTALL_NAME_BASE: "@rpath"
    scheme:
      testTargets:
        - CoderSDKTests
    dependencies: []

  CoderSDKTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: CoderSDKTests
    dependencies:
      - target: "Coder Desktop"
      - target: CoderSDK
        embed: false # Do not embed the framework.
      - package: Mocker
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Coder Desktop.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Coder Desktop"
        PRODUCT_BUNDLE_IDENTIFIER: com.coder.Coder-Desktop.CoderSDKTests

  VPNXPC:
    type: framework
    platform: macOS
    sources:
      - path: VPNXPC
    settings:
      base:
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        PRODUCT_NAME: "$(TARGET_NAME:c99extidentifier)"
        SWIFT_EMIT_LOC_STRINGS: YES
        GENERATE_INFOPLIST_FILE: YES
        DYLIB_COMPATIBILITY_VERSION: 1
        DYLIB_CURRENT_VERSION: 1
        DYLIB_INSTALL_NAME_BASE: "@rpath"
    dependencies: []
