// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: synchronization_core_mode.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// This file was taken from
// https://github.com/mutagen-io/mutagen/tree/v0.18.1/pkg/synchronization/core/mode.proto
//
// MIT License
// 
// Copyright (c) 2016-present Docker, Inc.
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// SynchronizationMode specifies the mode for synchronization, encoding both
/// directionality and conflict resolution behavior.
enum Core_SynchronizationMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  /// SynchronizationMode_SynchronizationModeDefault represents an unspecified
  /// synchronization mode. It is not valid for use with Reconcile. It should
  /// be converted to one of the following values based on the desired default
  /// behavior.
  case `default` // = 0

  /// SynchronizationMode_SynchronizationModeTwoWaySafe represents a
  /// bidirectional synchronization mode where automatic conflict resolution is
  /// performed only in cases where no data would be lost. Specifically, this
  /// means that modified contents are allowed to propagate to the opposite
  /// endpoint if the corresponding contents on the opposite endpoint are
  /// unmodified or deleted. All other conflicts are left unresolved.
  case twoWaySafe // = 1

  /// SynchronizationMode_SynchronizationModeTwoWayResolved is the same as
  /// SynchronizationMode_SynchronizationModeTwoWaySafe, but specifies that the
  /// alpha endpoint should win automatically in any conflict between alpha and
  /// beta, including cases where alpha has deleted contents that beta has
  /// modified.
  case twoWayResolved // = 2

  /// SynchronizationMode_SynchronizationModeOneWaySafe represents a
  /// unidirectional synchronization mode where contents and changes propagate
  /// from alpha to beta, but won't overwrite any creations or modifications on
  /// beta.
  case oneWaySafe // = 3

  /// SynchronizationMode_SynchronizationModeOneWayReplica represents a
  /// unidirectional synchronization mode where contents on alpha are mirrored
  /// (verbatim) to beta, overwriting any conflicting contents on beta and
  /// deleting any extraneous contents on beta.
  case oneWayReplica // = 4
  case UNRECOGNIZED(Int)

  init() {
    self = .default
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .default
    case 1: self = .twoWaySafe
    case 2: self = .twoWayResolved
    case 3: self = .oneWaySafe
    case 4: self = .oneWayReplica
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .default: return 0
    case .twoWaySafe: return 1
    case .twoWayResolved: return 2
    case .oneWaySafe: return 3
    case .oneWayReplica: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Core_SynchronizationMode] = [
    .default,
    .twoWaySafe,
    .twoWayResolved,
    .oneWaySafe,
    .oneWayReplica,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Core_SynchronizationMode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "SynchronizationModeDefault"),
    1: .same(proto: "SynchronizationModeTwoWaySafe"),
    2: .same(proto: "SynchronizationModeTwoWayResolved"),
    3: .same(proto: "SynchronizationModeOneWaySafe"),
    4: .same(proto: "SynchronizationModeOneWayReplica"),
  ]
}
