// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: synchronization_watch_mode.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// This file was taken from
// https://github.com/mutagen-io/mutagen/tree/v0.18.1/pkg/synchronization/watch_mode.proto
//
// MIT License
// 
// Copyright (c) 2016-present Docker, Inc.
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// WatchMode specifies the mode for filesystem watching.
enum Synchronization_WatchMode: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  /// WatchMode_WatchModeDefault represents an unspecified watch mode. It
  /// should be converted to one of the following values based on the desired
  /// default behavior.
  case `default` // = 0

  /// WatchMode_WatchModePortable specifies that native recursive watching
  /// should be used to monitor paths on systems that support it if those paths
  /// fall under the home directory. In these cases, a watch on the entire home
  /// directory is established and filtered for events pertaining to the
  /// specified path. On all other systems and for all other paths, poll-based
  /// watching is used.
  case portable // = 1

  /// WatchMode_WatchModeForcePoll specifies that only poll-based watching
  /// should be used.
  case forcePoll // = 2

  /// WatchMode_WatchModeNoWatch specifies that no watching should be used
  /// (i.e. no events should be generated).
  case noWatch // = 3
  case UNRECOGNIZED(Int)

  init() {
    self = .default
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .default
    case 1: self = .portable
    case 2: self = .forcePoll
    case 3: self = .noWatch
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .default: return 0
    case .portable: return 1
    case .forcePoll: return 2
    case .noWatch: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Synchronization_WatchMode] = [
    .default,
    .portable,
    .forcePoll,
    .noWatch,
  ]

}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension Synchronization_WatchMode: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "WatchModeDefault"),
    1: .same(proto: "WatchModePortable"),
    2: .same(proto: "WatchModeForcePoll"),
    3: .same(proto: "WatchModeNoWatch"),
  ]
}
