// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: synchronization_rsync_receive.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// This file was taken from
// https://github.com/coder/mutagen/tree/v0.18.3/pkg/synchronization/rsync/receive.proto
//
// MIT License
// 
// Copyright (c) 2016-present Docker, Inc.
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// ReceiverState encodes that status of an rsync receiver. It should be
/// considered immutable.
struct Rsync_ReceiverState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Path is the path currently being received.
  var path: String = String()

  /// ReceivedSize is the number of bytes that have been received for the
  /// current path from both block and data operations.
  var receivedSize: UInt64 = 0

  /// ExpectedSize is the number of bytes expected for the current path.
  var expectedSize: UInt64 = 0

  /// ReceivedFiles is the number of files that have already been received.
  var receivedFiles: UInt64 = 0

  /// ExpectedFiles is the total number of files expected.
  var expectedFiles: UInt64 = 0

  /// TotalReceivedSize is the total number of bytes that have been received
  /// for all files from both block and data operations.
  var totalReceivedSize: UInt64 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rsync"

extension Rsync_ReceiverState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ReceiverState"
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "path"),
    2: .same(proto: "receivedSize"),
    3: .same(proto: "expectedSize"),
    4: .same(proto: "receivedFiles"),
    5: .same(proto: "expectedFiles"),
    6: .same(proto: "totalReceivedSize"),
  ]

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.path) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.receivedSize) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.expectedSize) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.receivedFiles) }()
      case 5: try { try decoder.decodeSingularUInt64Field(value: &self.expectedFiles) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.totalReceivedSize) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 1)
    }
    if self.receivedSize != 0 {
      try visitor.visitSingularUInt64Field(value: self.receivedSize, fieldNumber: 2)
    }
    if self.expectedSize != 0 {
      try visitor.visitSingularUInt64Field(value: self.expectedSize, fieldNumber: 3)
    }
    if self.receivedFiles != 0 {
      try visitor.visitSingularUInt64Field(value: self.receivedFiles, fieldNumber: 4)
    }
    if self.expectedFiles != 0 {
      try visitor.visitSingularUInt64Field(value: self.expectedFiles, fieldNumber: 5)
    }
    if self.totalReceivedSize != 0 {
      try visitor.visitSingularUInt64Field(value: self.totalReceivedSize, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Rsync_ReceiverState, rhs: Rsync_ReceiverState) -> Bool {
    if lhs.path != rhs.path {return false}
    if lhs.receivedSize != rhs.receivedSize {return false}
    if lhs.expectedSize != rhs.expectedSize {return false}
    if lhs.receivedFiles != rhs.receivedFiles {return false}
    if lhs.expectedFiles != rhs.expectedFiles {return false}
    if lhs.totalReceivedSize != rhs.totalReceivedSize {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
