name: "Setup Nix devshell"
description: "This action sets up a nix devshell environment"
runs:
  using: "composite"
  steps:
    - name: Setup Nix
      uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16

    - name: Enter devshell
      uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
