name: "Setup Nix devshell"
description: "This action sets up a nix devshell environment"
runs:
  using: "composite"
  steps:
    - name: Setup Nix
      uses: nixbuild/nix-quick-install-action@25aff27c252e0c8cdda3264805f7b6bcd92c8718 # v29

    - name: Enter devshell
      uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
